language: c
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC
    - DEVKITARM=${DEVKITPRO}/devkitARM

cache:
  directories:
    - ${DEVKITPRO}

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${DEVKITPRO}"
  - wget http://download.sourceforge.net/devkitpro/devkitPPC_r29-1-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget https://download.sourceforge.net/devkitpro/devkitARM_r47-x86_64-linux.tar.bz2 -O devkitARM-linux.tar.bz2
  - wget https://github.com/Maschell/dynamic_libs/archive/lib.tar.gz -O dynamic_libs.tar.gz
  - wget https://github.com/Maschell/libutils/archive/master.tar.gz -O libutils.tar.gz
  - wget https://github.com/aliaspider/libfat/archive/master.tar.gz -O libfat.tar.gz
  - wget https://github.com/dimok789/libiosuhax/archive/master.tar.gz -O libiosuhax.tar.gz
  - wget https://github.com/Maschell/libntfs-wiiu/archive/master.tar.gz -O libntfs.tar.gz
  - wget https://github.com/Maschell/fs_wrapper/archive/master.tar.gz -O fs_wrapper.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xjf devkitARM-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xzvf dynamic_libs.tar.gz
  - tar -xzvf libutils.tar.gz
  - tar -xzvf libfat.tar.gz
  - tar -xzvf libiosuhax.tar.gz
  - tar -xzvf libntfs.tar.gz
  - tar -xzvf fs_wrapper.tar.gz
  - 7z x -y ./dynamic_libs-lib/libs/portlibs.zip -o${DEVKITPRO}
  - (cd libiosuhax-master && make -j8 && make install)
  - (cd libfat-master && make wiiu-release && make wiiu-install)
  - (cd libntfs-wiiu-master && make wiiu-install)
  - (cd dynamic_libs-lib && make -j8 && make install)
  - (cd libutils-master && make -j8 && make install)
  - (cd fs_wrapper-master && make -j8 && make install)
script:
- sudo make


deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key: $KEY
  file: sdcafiine.elf
  draft: true
